# Generated by Django 4.2 on 2023-07-28 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="fooddiaryentry", name="date",),
        migrations.AddField(
            model_name="fooddiaryentry",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
