# Generated by Django 4.2.3 on 2023-07-10 13:06

from django.db import migrations, models
import response.models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='history',
            field=models.JSONField(default=response.models.get_default_history),
        ),
    ]
