# Generated by Django 4.2.3 on 2023-07-12 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('goal', models.CharField(blank=True, choices=[('bulk', 'Bulk'), ('lose_weight', 'Lose weight'), ('healthy_happiness', 'Healthy happiness'), ('improve_posture', 'Improve posture'), ('stress_reduction', 'Stress reduction'), ('improve_flexibility', 'Improve flexibility'), ('improve_endurance', 'Improve endurance'), ('six_pack', 'Six Pack')], max_length=20, null=True)),
                ('activity_level', models.CharField(blank=True, choices=[('sedentary', 'Sedentary (little or no exercise, desk job)'), ('lightly_active', 'Lightly Active (light exercise/sports 1-3 days/wk)'), ('moderately_active', 'Moderately Active (moderate exercise/sports 6-7 days/wk)'), ('very_active', 'Very Active (hard exercise every day, or 2x/day)'), ('extra_active', 'Extra Active (hard exercise 2+ hrs/day, training for marathon, triathlon, etc.)')], max_length=20, null=True)),
                ('determination_level', models.CharField(blank=True, choices=[('casual', 'Casual'), ('determined', 'Determined'), ('very_determined', 'Very Determined')], max_length=20, null=True)),
                ('bmr_type', models.CharField(blank=True, choices=[('mifflin_st_jeor', 'Mifflin-St Jeor'), ('harris_benedict', 'Harris-Benedict'), ('katch_mcardle', 'Katch-McArdle')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
