# Generated by Django 4.2.3 on 2023-07-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='body_fat_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
