# Generated by Django 4.2.3 on 2023-07-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_body_fat_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='body_fat_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
