# Generated by Django 4.2.3 on 2023-07-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofile_body_fat_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='initial_plan',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
